react-hookz/web

.eslintrc.js
CHANGELOG.md

The `CHANGELOG.md` kept getting linted
Added it as an exception

docs: exclude CHANGELOG.md from linting

---

stories/useUnmountEffect.stories.tsx

The useMountEffect example triggers a dialogue when you leave the page by default, which is super annoying.
The useMountEffect example now requires user interaction before triggering a dialogue.

fix: default useUnmountEffect example to false

---

README.md
src/index.ts
src/useConditionalEffect.ts
src/useConditionalUpdateEffect.ts
src/useUpdateEffect.ts
src/util/const.ts
stories/useConditionalEffect.stories.tsx
stories/useConditionalEffect.story.mdx
stories/useConditionalUpdateEffect.stories.tsx
stories/useConditionalUpdateEffect.story.mdx
stories/useIsMounted.stories.tsx
stories/useUnmountEffect.stories.tsx
tests/dom/useConditionalEffect.test.ts
tests/dom/useConditionalUpdateEffect.test.ts
tests/ssr/useConditionalEffect.test.ts
tests/ssr/useConditionalUpdateEffect.test.ts

- `useConditionalEffect`  - Alike `useEffect` but callback invoked only if conditions match predicate.
- `useConditionalUpdateEffect` — Alike useUpdateEffect but callback invoked only if conditions match predicate.

feat: new hooks, useConditionalEffect and useConditionalUpdateEffect

---

README.md

Hooks list in README didn't line up with storybook.
The hooks list now lines up with storybook.

docs: alphabetize hooks README like storybook

---

CONTRIBUTING.md
README.md
src/useNetworkState.ts
src/util/misc.ts
stories/useMediatedState.story.mdx
stories/useNetworkState.stories.tsx
stories/useNetworkState.story.mdx
tests/dom/useNetworkState.test.ts
tests/dom/util/misc.test.ts
tests/ssr/useNetworkState.test.ts

Tracks the state of browser's network connection.

feat: new hook, useNetworkState

---

README.md
src/index.ts
src/useMediatedState.ts
src/useSyncedRef.ts
stories/Miscellaneous/useSyncedRef.stories.tsx
stories/Miscellaneous/useSyncedRef.story.mdx
tests/dom/useSyncedRef.test.ts
tests/ssr/useSyncedRef.test.ts

Like `useRef`, but it returns immutable ref that contains actual value.
I'm not sure about hook naming, i dont really like the `useSyncedRef`, but it is the best i came up with. 

feat: new hook `useSyncedRef`

---

.eslintrc.js
README.md
src/index.ts
src/useRafCallback.ts
stories/Callback/useRafCallback.stories.tsx
stories/Callback/useRafCallback.story.mdx
stories/State/useMediatedState.story.mdx
stories/State/useSafeState.story.mdx
stories/State/useToggle.story.mdx
tests/dom/useNetworkState.test.ts
tests/dom/useRafCallback.test.ts
tests/ssr/useNetworkState.test.ts
tests/ssr/useRafCallback.test.ts

Makes passed function to be called within next animation frame.
- #33

feat: new hook `useRafCallback`

---

.npmignore
package.json

The `types` folder is not published. I think this should do it.

Remove `types` field in package.json

---

README.md
src/index.ts
src/useResizeObserver.ts
stories/Sensor/useResizeObserver.stories.tsx
stories/Sensor/useResizeObserver.story.mdx
tests/dom/useResizeObserver.test.ts
tests/ssr/useResizeObserver.test.ts

Invokes a callback whenever ResizeObserver detects a change to target's size.
- #33

feat: new hook `useResizeObserver`

---

README.md
src/useMeasure.ts
stories/Sensor/useMeasure.stories.tsx
stories/Sensor/useMeasure.story.mdx
stories/Sensor/useResizeObserver.stories.tsx
tests/dom/useMeasure.test.ts
tests/ssr/useMeasure.test.ts

Uses ResizeObserver to track element dimensions and re-render component when they change.
- #33

feat: new hook `useMeasure`

---

.github/workflows/ci-cd.yml
jest.config.js
package.json

Distibution bundle is not tested.
Tests should be performed against tests.
Added projects to jest, and used `moduleNameMapper` feature to repalce the sources with bundle.
- #103

test: add tests against distribution bundle

---

README.md
package.json
src/index.ts
src/useCookie/__docs__/example.stories.tsx
src/useCookie/__docs__/story.mdx
src/useCookie/__tests__/dom.tsx
src/useCookie/__tests__/ssr.tsx
src/useCookie/useCookie.ts
yarn.lock

Manages a single cookie.
- #33

feat: new hook `useCookie`

---

README.md
src/index.ts
src/useDebouncedCallback/__docs__/example.stories.tsx
src/useDebouncedCallback/__docs__/story.mdx
src/useDebouncedCallback/__tests__/dom.ts
src/useDebouncedCallback/__tests__/ssr.ts
src/useDebouncedCallback/useDebouncedCallback.ts
src/useRafCallback/__tests__/dom.ts
src/useResizeObserver/__docs__/example.stories.tsx
src/useThrottledCallback/__docs__/example.stories.tsx
src/useThrottledCallback/__docs__/story.mdx
src/useThrottledCallback/__tests__/dom.ts
src/useThrottledCallback/__tests__/ssr.ts
src/useThrottledCallback/useThrottledCallback.ts
src/useValidator/__docs__/example.stories.tsx

`useDebounceCallback` and `useThrottleCallback` are not correctly named.
It should be `useDebouncedCallback` and `useThrottledCallback`
Renames tese hooks and ther import\use occurrences.
- #129

fix: rename useThrottleCallback and useDebounceCallback

---

src/useDebouncedCallback/__docs__/example.stories.tsx
src/useDebouncedCallback/__docs__/story.mdx
src/useDebouncedCallback/__tests__/dom.ts
src/useDebouncedCallback/useDebouncedCallback.ts

`maxWait` defines maximum amount of milliseconds that function can be delayed before it's force execution. 0 means no max wait (default).
**should be merged after #130**

feat: add `maxWait` parameter to `useDebouncedCallback` hook

---

src/useDebouncedCallback/__docs__/example.stories.tsx
src/useDebouncedCallback/__docs__/story.mdx
src/useDebouncedCallback/__tests__/dom.ts
src/useDebouncedCallback/__tests__/ssr.ts
src/useDebouncedCallback/useDebouncedCallback.ts
src/useThrottledCallback/__docs__/example.stories.tsx
src/useThrottledCallback/__docs__/story.mdx
src/useThrottledCallback/__tests__/dom.ts
src/useThrottledCallback/__tests__/ssr.ts
src/useThrottledCallback/useThrottledCallback.ts

`useThrottledCallback` and `useDebouncedCallback` has different arguments order comparing to `useCallback` (delay argument is before deps list). It is mentally harder to handle such differences.
BREAKING CHANGE:
`delay` and `deps` arguments are swapped position for `useThrottledCallback` and `useDebouncedCallback` hooks to be aligned with `useCallback` signature.
**merge after #131**

feat: change args for `useThrottledCallback` and `useDebouncedCallback`

---

README.md
src/index.ts
src/useDebouncedEffect/__docs__/example.stories.tsx
src/useDebouncedEffect/__docs__/story.mdx
src/useDebouncedEffect/__tests__/dom.ts
src/useDebouncedEffect/__tests__/ssr.ts
src/useDebouncedEffect/useDebouncedEffect.ts
src/useDebouncedState/__docs__/example.stories.tsx
src/useDebouncedState/__docs__/story.mdx
src/useDebouncedState/__tests__/dom.ts
src/useDebouncedState/__tests__/ssr.ts
src/useDebouncedState/useDebouncedState.ts
src/useSafeState/useSafeState.ts

- `useDebouncedEffect` — Like `useEffect`, but passed function is debounced.
- `useDebouncedState` — Lise `useSafeState` but its state setter is debounced.

feat: new hooks `useDebouncedEffect` and `useDebouncedState`

---

src/useAsync/useAsync.ts
src/util/misc.ts

`useAsync` return state now properly handles presence of `initialState`
option.
- #134

fix: improve `useAsync` typings

---

README.md
src/index.ts
src/useDebouncedState/__docs__/example.stories.tsx
src/useThrottledCallback/__docs__/story.mdx
src/useThrottledCallback/useThrottledCallback.ts
src/useThrottledEffect/__docs__/example.stories.tsx
src/useThrottledEffect/__docs__/story.mdx
src/useThrottledEffect/__tests__/dom.ts
src/useThrottledEffect/__tests__/ssr.ts
src/useThrottledEffect/useThrottledEffect.ts
src/useThrottledState/__docs__/example.stories.tsx
src/useThrottledState/__docs__/story.mdx
src/useThrottledState/__tests__/dom.ts
src/useThrottledState/__tests__/ssr.ts
src/useThrottledState/useThrottledState.ts

`useThrottledEffect` - Like `useEffect`, but passed function is throttled.
`useThrottledState` - Like `useSafeState` but its state setter is throttled.

feat: new hooks `useThrottledEffect` and `useThrottledState`

---

README.md
src/index.ts
src/usePermission/__docs__/example.stories.tsx
src/usePermission/__docs__/story.mdx
src/usePermission/__tests__/dom.ts
src/usePermission/__tests__/ssr.ts
src/usePermission/usePermission.ts

Tracks a permission state.
- #33

feat: new hook `usePermission`

---

README.md
src/index.ts
src/useClickOutside/__docs__/example.stories.tsx
src/useClickOutside/__docs__/story.mdx
src/useClickOutside/__tests__/dom.ts
src/useClickOutside/__tests__/ssr.ts
src/useClickOutside/useClickOutside.ts

Triggers callback when user clicks outside the target element.
- #33

feat: new hook `useClickOutside`

---

README.md
src/index.ts
src/useMap/__docs__/example.stories.tsx
src/useMap/__docs__/story.mdx
src/useMap/__tests__/dom.ts
src/useMap/__tests__/ssr.ts
src/useMap/useMap.ts

Tracks the state of a `Map`.
- #33

feat: new hook `useMap`

---

src/useResizeObserver/__tests__/dom.ts
src/useResizeObserver/useResizeObserver.ts

Now listeners invoked asynchronously so none of them waiting other's invocation.

feat: improve `useResizeObserver`

---

src/useEventListener/__tests__/dom.ts
src/useEventListener/useEventListener.ts

React already handles the changes inside refs, therefore there is no need to unwrap ref on each render.

feat: improve `useEventListener`

---

README.md
src/index.ts
src/useIntersectionObserver/__docs__/example.stories.tsx
src/useIntersectionObserver/__docs__/story.mdx
src/useIntersectionObserver/__tests__/dom.ts
src/useIntersectionObserver/__tests__/ssr.ts
src/useIntersectionObserver/useIntersectionObserver.ts

Tracks intersection of a target element with an ancestor element or with a top-level document's viewport.
- #33

feat: new hook useIntersectionObserver

---

src/index.ts
src/useConditionalEffect/__docs__/example.stories.tsx
src/useConditionalEffect/__docs__/story.mdx
src/useConditionalEffect/__tests__/dom.ts
src/useConditionalEffect/__tests__/ssr.ts
src/useConditionalEffect/useConditionalEffect.ts
src/useConditionalUpdateEffect/__docs__/example.stories.tsx
src/useConditionalUpdateEffect/__docs__/story.mdx
src/useConditionalUpdateEffect/__tests__/dom.ts
src/useConditionalUpdateEffect/__tests__/ssr.ts
src/useConditionalUpdateEffect/useConditionalUpdateEffect.ts
src/util/const.ts

Add `deps` argument for `useConditionalUpdateEffect` and `useConditionalEffect` hooks
BREAKING CHANGE: `useConditionalUpdateEffect` and `useConditionalEffect` now has changed call signature (new argument).
- #157

Add `deps` argument for `useConditionalUpdateEffect` and `useConditionalEffect` hooks

---

README.md
migrating-from-react-use.md
src/__docs__/migrating-from-react-use.story.mdx

A lot of our users are coming from `react-use`. A migration guide might help them move quicker.
I created a migration guide.

docs: create migration guide for react-use

---

src/index.ts
src/useCookieValue/__docs__/story.mdx
src/useCookieValue/__tests__/dom.ts
src/useCookieValue/__tests__/ssr.ts

Because of optional dependency it would break the build in case of `js-cookie` absence.
BREAKING CHANGE: `useCookieValue` is no more exported from index file.

fix: remove `useCookieValue` from index

---

src/useMediaQuery/__tests__/dom.ts
src/useMediaQuery/useMediaQuery.ts

As Safari 13- has obsolete MediaQueryList API - it requires some extra checks.
Shpould Work on safari 13-
Check `addEventListener` and `removeEventListener` methods existence and fallback to `addListener` and `removeListener` respectively.
- Close: #242

fix(useMediaQuery): add support for safari 13-

---

src/index.ts
src/useNetworkState/useNetworkState.ts
src/usePermission/usePermission.ts
yarn.lock

BREAKING CHANGE: `IAnyPermissionDescriptor` type removed in favor of
built-in `PermissionDescriptor`.
Close: #290

chore(TS): migrate to TypeScript 4.4

---

src/useMeasure/__docs__/story.mdx

There was a small typo in the `useMeasure` docs
Fixes the typo

docs: fix typo in useMeasure docs

---

src/useIntersectionObserver/__docs__/story.mdx

There was a typo in the `useIntersectionObserver` docs
Fixes the typo

docs: fix typo in `useIntersectionObserver` docs

---

src/__docs__/migrating-from-react-use.story.mdx

The migration guide was outdated
Updated migration guide with `useIntersectionObserver` and `useKeyboardEvent`

docs: update migration guide with `useIntersectionObserver` and `useKeyboardEvent`

---

src/__docs__/migrating-from-react-use.story.mdx
src/useNetworkState/__docs__/story.mdx

Invalid hook name in docs, aslthough it is properly named in code.
Fixes #251 
- #251

docs(useNetworkState): proper hook naming in docs

---

src/index.ts
src/useAsync/__docs__/example.stories.tsx
src/useAsync/__docs__/story.mdx
src/useAsync/__tests__/dom.ts
src/useAsync/__tests__/ssr.ts
src/useAsync/useAsync.ts

Use composition with effectors for such functionality.
BREAKING CHANGE:
`useAsync` hook now has only 2 arguments, `asyncFn` and `initialValue`
and do not execute provided function on its own.
Remove effector functionality and unnecessary arguments.
- #317

feat(useAsync): remove effector behaviour from hook

---

README.md
src/index.ts
src/useAsync/__docs__/example.stories.tsx
src/useAsync/__docs__/story.mdx
src/useAsync/useAsync.ts
src/useAsyncAbortable/__docs__/example.stories.tsx
src/useAsyncAbortable/__docs__/story.mdx
src/useAsyncAbortable/__tests__/dom.ts
src/useAsyncAbortable/__tests__/ssr.ts
src/useAsyncAbortable/useAsyncAbortable.ts
src/util/misc.ts

Like `useAsync`, but also provides `AbortSignal` as first function argument to async function.

feat: new hook `useAsyncAbortable`

---

src/useStorageValue/useStorageValue.ts

Puts event handles registretion into layout effect instead of common effector
- #451 
Somewhy i cant manage tests to work for this case. State is updated but not for tests.

fix(451): attempt to fix issue #451

---

src/useMeasure/__docs__/story.mdx
src/useMeasure/useMeasure.ts
src/useResizeObserver/__docs__/story.mdx
src/useResizeObserver/__tests__/dom.ts
src/useResizeObserver/useResizeObserver.ts

Added extra parameter that allows to enable/disable observation dynamically.
- #523

feat(useMeasure,useResizeObserver): ability yo disable observation

---

src/useLocalStorageValue/useLocalStorageValue.ts
src/useSessionStorageValue/useSessionStorageValue.ts

Adds storage access check to replace hook with noop functionality.
- #521

fix(`useLocalStorage`, `useSessionStorage`): replace hook with noop in case of storage absence.

---

src/index.ts
src/usePrevious/__docs__/example.stories.tsx
src/usePrevious/__docs__/story.mdx
src/usePrevious/__tests__/dom.ts
src/usePreviousDistinct/__docs__/example.stories.tsx
src/usePreviousDistinct/__docs__/story.mdx
src/usePreviousDistinct/__tests__/dom.ts
src/usePreviousDistinct/__tests__/ssr.ts
src/usePreviousDistinct/usePreviousDistinct.ts
src/util/const.ts

Outlined in #33 and [here](https://github.com/streamich/react-use/blob/master/docs/usePreviousDistinct.md).
While I haven't needed this hook myself, I began understanding the value and differences `usePrevious` and `usePreviousDistinct` offer. I feel like people who reach for `usePrevious` may wish to know that `usePreviousDistinct` exists. I may not have done well on that front, but wanted to give it a go.
- #33

feat: new hook `usePreviousDistinct`

---

README.md

`usePreviousDistinct` was missing from README
Add `usePreviousDistinct` to README

Add `usePreviousDistinct` to README

---

src/useCustomCompareEffect/__docs__/example.stories.tsx

As noted in #352, no story exists for `useCustomCompareEffect`.
It adds the requested story
- #352 
Resolves #352

docs(useCustomCompareEffect): Add story

---

README.md

Link for useNetworkState in README is broken
Changed it with the correct one

docs: fix broken link for useNetworkState

---

README.md
src/index.ts
src/usePreviousDistinct/usePreviousDistinct.ts
src/useScreenOrientation/__docs__/example.stories.tsx
src/useScreenOrientation/__docs__/story.mdx
src/useScreenOrientation/__tests__/dom.ts
src/useScreenOrientation/__tests__/ssr.ts
src/useScreenOrientation/useScreenOrientation.ts
src/util/const.ts

Checks if screen is in `portrait` or `landscape` orientation and automatically re-renders on orientation change.
- #33

feat: implement new hook - `useScreenOrientation`

---

src/useMediaQuery/__docs__/story.mdx
src/useMediaQuery/__tests__/dom.ts
src/useMediaQuery/useMediaQuery.ts

BREAKING CHANGE: `useMediaQuery` now does synchronous fetch, this means
that in browser it will return final state on first render, while SSR
mode still return `undefined`.
SSR users should set second parameter of this hook to `true`, to
postpone state fetch until effects phase.

feat(`useMediaQuery`): add synchronous mql state fetch

---

README.md
src/index.ts
src/useRafState/__docs__/example.stories.tsx
src/useRafState/__docs__/story.mdx
src/useRafState/__tests__/dom.ts
src/useRafState/__tests__/ssr.ts
src/useRafState/useRafState.ts

Like `React.useState`, but state is only updated within animation frame.
- #33

feat: implement `useRafState` hook

---

README.md
src/index.ts
src/useRafEffect/__docs__/example.stories.tsx
src/useRafEffect/__docs__/story.mdx
src/useRafEffect/__tests__/dom.ts
src/useRafEffect/__tests__/ssr.ts
src/useRafEffect/useRafEffect.ts

Like `React.useEffect`, but effect is only run within animation frame.
-https://github.com/react-hookz/web/issues/33

feat: create `useRafEffect`

---

src/useRerender/__tests__/dom.ts
src/useRerender/useRerender.ts

Even amount of `useRerender` calls causes no rerender.
`useRerender` should cause rereder in any case
Replace boolean switch with integer incrementation. Also it is guarded from overflow.
- #691

fix: make `useRerender` operate integer increment instead of bool switch

---

src/__docs__/migrating-from-react-use.story.mdx

It works like `useSafeState`, except it will return the provided default value when the state is set to `undefined` or `null`.
- #33

docs(useDefault): Suggest `useMediatedState` instead 

---

README.md
src/__docs__/migrating-from-react-use.story.mdx
src/index.ts
src/useCounter/__docs__/example.stories.tsx
src/useCounter/__docs__/story.mdx
src/useCounter/__tests__/dom.ts
src/useCounter/__tests__/ssr.ts
src/useCounter/useCounter.ts

This hook tracks a numeric value and offers functions for manipulating it.
The exact same API from `react-use` is retained.
- #33

feat(useCounter): port `useCounter` from `react-use`

---

src/useUnmountEffect/__tests__/dom.ts
src/useUnmountEffect/useUnmountEffect.ts

fix #756
Use `useSyncedRef` to handle effector changes.
- #756

fix: `useUnmountEffect` now invokes changing effect functions

---

src/useMeasure/useMeasure.ts
src/useResizeObserver/__tests__/dom.ts
src/useResizeObserver/useResizeObserver.ts

fix: `useResizeObserver` now respects element changes within ref object

---

src/useRerender/useRerender.ts

First add one to state and then get reminder of max safe integer
Modulo is never applied
Number is always smaller than MAX_SAFE_INTEGER
It applies correct order of operations 

fix: Apply correct order of operations in `useRerender`

---

src/useMediaQuery/__docs__/example.stories.tsx
src/useMediaQuery/__docs__/story.mdx
src/useMediaQuery/__tests__/dom.ts
src/useMediaQuery/useMediaQuery.ts
src/useScreenOrientation/useScreenOrientation.ts

In concurrent mode along with strict mode - synchronous mql state fetch 
leads to state stuck. The only way to fix that behaviour is to switch 
back to fully asynchronous code.
Upsides - way simpler code, and reduced amount of it.
Due to changes `useScreenOrientation` also affected.
- fix #849

fix(useMediaQuery): fix state stuck for concurrent mode

---

src/useToggle/__docs__/example.stories.tsx
src/useToggle/__docs__/story.mdx
src/useToggle/__tests__/dom.ts
src/useToggle/useToggle.ts

BREAKING CHANGE: `useToggle` now ignores react events passed to its
state setter, so it can be used as event handler directly.
- fix #861

feat(useToggle): ignore react events passed to state setter

---

README.md
src/index.ts
src/useControlledRerenderState/__docs__/example.stories.tsx
src/useControlledRerenderState/__docs__/story.mdx
src/useControlledRerenderState/__tests__/dom.ts
src/useControlledRerenderState/__tests__/ssr.ts
src/useControlledRerenderState/useControlledRerenderState.ts
src/useHookableRef/useHookableRef.ts

Like `React.useState`, but its state setter accepts extra argument, that allows to cancel rerender.

feat: implement `useControlledRerenderState` hook

---

README.md
src/__docs__/migrating-from-react-use.story.mdx
src/index.ts
src/useTimeoutEffect/__docs__/example.stories.tsx
src/useTimeoutEffect/__docs__/story.mdx
src/useTimeoutEffect/__tests__/dom.ts
src/useTimeoutEffect/__tests__/ssr.ts
src/useTimeoutEffect/useTimeoutEffect.ts

Functions like `setTimeout`, except in hook form. Returns a method to cancel the timeout, and a method to restart the timeout. It does not cause any rerenders.
- https://github.com/react-hookz/web/issues/33

feat(useTimeoutEffect): Implement useTimeoutEffect

---

src/useDeepCompareEffect/__docs__/example.stories.tsx

`useDeepCompareEffect` has no example. I accidently came up with one when trying to figure out an example for `useDeepCompareMemo`. This example requires the user to open their browser console and check out the example code, but I think it gets the point across.
Adds an example.
- Closes #582

docs(Add example for useDeepCompareEffect)

---

src/__docs__/migrating-from-react-use.story.mdx

`useWindowSize` was listed as not implemented in the migration guide
Migration guide now links to `useWindowSize` doc

fix: migration guide

---

src/useLocalStorageValue/__docs__/example.stories.tsx
src/useLocalStorageValue/__docs__/story.mdx
src/useSessionStorageValue/__docs__/example.stories.tsx
src/useSessionStorageValue/__docs__/story.mdx
src/useSessionStorageValue/useSessionStorageValue.ts
src/useStorageValue/useStorageValue.ts

The API of `useStorageValue` has changed. The changes need to be reflected in the documentation of `useSessionStorageValue` and `useLocalStorageValue`.
Modify the relevant pieces of the docs. Please make sure that I did not miss anything.
Also, do the current examples seem a bit weird to you? They don't really persist the values the user types into the inputs and you cannot see anything come up in storages. But I guess that is because the example is in an iframe (but don't the iframe and the docs page come from the same domain? Then the iframe should be able to access the parent's storages).
Relates to #960

Add docs for the new API of useSessionStorageValue and useLocalStorageValue

---

src/useCustomCompareMemo/__docs__/story.mdx
src/useCustomCompareMemo/useCustomCompareMemo.ts

Described in #975.
Described in #975.
Change the type of the `useCustomCompareMemo` factory function to include a generic type parameter for the return type. This generic type is then passed to the underlying `useMemo`, guaranteeing correct return type.
- #975

fix(useCustomCompareMemo): Correctly infer factory function return type

---

README.md
src/__docs__/Introduction.story.mdx

I wanted a link to Github from the docs, as I'd often find myself going from one to the other.
I also wanted to make it clearer that our intention is to be a spiritual successor of react-use, as someone in Discord pointed out

Add Github link to docs, mention `react-use` next to `migration guide`

---

README.md
src/index.ts
src/useDeepCompareEffect/__docs__/story.mdx
src/useDeepCompareMemo/__docs__/example.stories.tsx
src/useDeepCompareMemo/__docs__/story.mdx
src/useDeepCompareMemo/__tests__/dom.ts
src/useDeepCompareMemo/__tests__/ssr.ts
src/useDeepCompareMemo/useDeepCompareMemo.ts

Memoizes a value just like `useMemo`, but determines dependency changes by using a deep equality check (the `isEqual` function from react-hook/deep-equal) instead of a reference check.
- #871

feat(useDeepCompareMemo): Implement useDeepCompareMemo

---

src/useLocalStorageValue/__docs__/example.stories.tsx
src/useLocalStorageValue/__docs__/story.mdx
src/useSessionStorageValue/__docs__/example.stories.tsx
src/useSessionStorageValue/__docs__/story.mdx
src/useStorageValue/__tests__/ssr.ts
src/useStorageValue/useStorageValue.ts

`initializeWithValue` default value is not respected. It is always read from user-given `options`, meaning that it is `undefined` (effectively `false`), if the user did not explicitly set it.
Reproduction steps are given in #1002 . It looks like `initializeWithValue` is `false` by default (which is what the bug report is about), but actually it's just that the default value of `true` is not respected.
Additionally, I noticed that the default value for `initializeWithValue` is set to `true`, which partly contradicts the documentation (in the top part of the docs of `useSessionStorageValue` and `useLocalStorageValue` `initializeWithValue` is said to be `false` by default, but in the description of the `options` argument it is said to be `true`) and the tests. After fixing `useStorageValue` …

Fix `initializeWithValue` default not respected, fix docs and tests

---

src/useStorageValue/__tests__/dom.ts
src/useStorageValue/useStorageValue.ts

`useStoageValue` methods are not stable between renders, after state change.
Methods should not change between renders
Wrap methods with `useMemo` and interpolate them into returned object.
- #1014

fix(useStorageValue): make methods to be stable between renders

---

src/__docs__/migrating-from-react-use.story.mdx

In #33 it was decided that location-related hooks will not be ported, since those are already provided by the various routing libraries available.
Add a mention about this decision to the migration guide.
- #33 
Closes #992

docs(migrating-from-react-use): Add mention about not porting location-related hooks

---

CONTRIBUTING.md
README.md
src/__docs__/Introduction.story.mdx
src/useAsync/__docs__/story.mdx
src/useAsync/useAsync.ts
src/useAsyncAbortable/__docs__/story.mdx
src/useAsyncAbortable/useAsyncAbortable.ts
src/useCookieValue/__docs__/story.mdx
src/useCookieValue/useCookieValue.ts
src/useLocalStorageValue/__docs__/story.mdx
src/useSafeState/useSafeState.ts
src/useSessionStorageValue/__docs__/story.mdx
src/useStorageValue/useStorageValue.ts

When I first discovered this repo, the only thing I disliked was that the language in the docs was a bit cluncky at times.
Since good docs are really important for any library, I figured that I might go through them and attempt to improve them as much as I can. I am by no means a native english speaker, so there surely will remain room for improvement.
I plan on going through all of the docs over a few pull requests, so that a single pull request would not get too big to review.
Note that I am attempting to only fix typos and improve the general language, not change what is said in the docs.
Fix typos and improve the language in:
- README.md
- CONTRIBUTING.md
- The introduction page
- All of the hooks in the State category

Fix typos and improve language in docs

---

src/__docs__/migrating-from-react-use.story.mdx

I presume useUpsert is not going to be ported since useList already provides an upsert function.

docs(migrating-from-react-use): Add mention about not porting useUpsert

---

.github/PULL_REQUEST_TEMPLATE/new-hook.md
CONTRIBUTING.md

Sometimes PR's for new hooks are submitted and they are rejected, because the hooks have no valid use-case. This is
often the case for hooks ported from `react-use`.
This is of course unfortunate for the contributors who end up wasting time writing code that will not be merged.
- Added a section to the PR template asking to check #33 and the migration guide to see whether a hook from `react-use` has been approved for porting.
- Added a section to the PR template asking a valid use-case to be provided for all new hooks.
- Added a small section to the contribution guide with some general notes about porting hooks from `react-use`, including everything that was added to the PR template.

Update PR template and contribution guide in regards to submitting new hooks

---

src/useThrottledCallback/index.ts

- NextJS application
- Use `useThrottledCallback` anywhere
- Notice that it's only called once and then never again
Method should be called and limited to throttling frequency.
Clears the timeout properly.

fix(useThrottleCallback): Cleared timeout on unmount

---

src/useDebouncedCallback/__docs__/story.mdx
src/useDebouncedCallback/__tests__/dom.ts
src/useDebouncedCallback/index.ts

fix(useDebouncedCallback): make invoked function to be updated with deps

---

eslint.config.js
package.json
src/useAsync/index.ts
src/useAsyncAbortable/index.ts
src/useClickOutside/index.ts
src/useCustomCompareEffect/index.ts
src/useCustomCompareMemo/index.ts
src/useDebouncedCallback/index.ts
src/useEventListener/index.ts
src/useHookableRef/index.ts
src/useIntersectionObserver/index.ts
src/useKeyboardEvent/index.ts
src/useLifecycleLogger/index.ts
src/useMap/index.ts
src/useMediaQuery/index.ts
src/usePrevious/index.ts
src/useResizeObserver/index.ts
src/useSet/index.ts
src/useThrottledCallback/index.ts
yarn.lock

Change adapts to types changes of React19. Otherwise no changes done. Deprecated `MutableRefObject` remained to ensure backwards compatibility.
Adresses #1573

feat: add typing support for react 19

---

package.json
src/useDeepCompareEffect/index.ts
src/useDeepCompareMemo/index.ts
yarn.lock

`@react-hookz/deep-equal` been deprecated in favor of [`@ver0/deep-equal`](https://github.com/ver0-project/deep-equal)

fix: migrate to @ver0/deep-equal
