- .eslintrc.js
- src/index.ts
- src/useToggle.ts
- src/util/resolveHookState.ts
- tests/dom/useToggle.ts
- tests/dom/util/resolveHookState.ts
- tests/ssr/useToggle.ts
- tsconfig.json
Stateful hook that can become only true or false. It's `setState` action toggles state in case called without parameter or with `undefined`.
Also supports functional updfates as regular `setState`
> feat: useToggle hook

- CHANGELOG.md
- README.md
Some of the README pages don't read quite right to me
I suggest some small fixes
> docs: suggested language changes to README

- .editorconfig
- CHANGELOG.md
- CONTRIBUTING.md
> docs: introduce CONTRIBUTING.md

- CONTRIBUTING.md
- README.md
- src/useRerender.ts
- stories/useFirstMountState.stories.tsx
- stories/useFirstMountState.story.mdx
- stories/useMountEffect.stories.tsx
- stories/useMountEffect.story.mdx
- stories/useRerender.stories.tsx
- stories/useRerender.story.mdx
- stories/useToggle.stories.tsx
- stories/useToggle.story.mdx
- stories/useUnmountEffect.stories.tsx
- stories/useUnmountEffect.story.mdx
- stories/useUpdateEffect.stories.tsx
- stories/useUpdateEffect.story.mdx
Docs were missing for some components
> docs: docs for some docless components

- README.md
- src/index.ts
- src/usePrevious.ts
- stories/usePrevious.stories.tsx
- stories/usePrevious.story.mdx
- tests/dom/usePrevious.test.ts
- tests/ssr/usePrevious.test.ts
Returns the value passed to the hook on previous render.
> feat: new hook usePrevious

- README.md
- package.json
- src/index.ts
- src/useMediatedState.ts
- stories/useMediatedState.stories.tsx
- stories/useMediatedState.story.mdx
- tests/dom/useMediatedState.test.ts
- tests/ssr/useMediatedState.test.ts
- yarn.lock
Like `useState`, but every value set is passed through mediator function.
> feat: new hook useMediatedState

- README.md
- src/index.ts
- src/useIsomorphicLayoutEffect.ts
- stories/useIsomorphicLayoutEffect.story.mdx
- tests/dom/useIsomorphicLayoutEffect.test.ts
- tests/ssr/useIsomorphicLayoutEffect.test.ts
Alias for `useLayoutEffect` in browser, but for `useEffect` at server side. Helps to avoid warning shown during SSR.
> feat: new hook `useIsomorphicLayoutEffect`

- .github/workflows/discord-release-notify.yml
Thanks for the PR!
To better assist you, please select the type of PR you want to create.
Click the "Preview" tab above, and click on the link for the PR type:
- [🐛 Bug Fix](?template=bug-fix.md)
- [👍 New Hook](?template=new-hook.md)
- [📓 Documentation Fix](?template=documentation.md)
> feat: add discord release notify action

- src/index.ts
- src/useTitle.ts
- stories/Dom/useTitle.stories.tsx
- stories/Dom/useTitle.story.mdx
- tests/dom/useTitle.test.ts
- tests/ssr/useTitle.test.ts
> feat: new hook `useTitle`

- .eslintrc.js
- src/useDebounceCallback/__tests__/dom.ts
- src/useDebounceCallback/useDebounceCallback.ts
- src/useRafCallback/__tests__/dom.ts
- src/useRafCallback/useRafCallback.ts
- yarn.lock
Previous implementation returned wrapped function that has no name and 0 length, meaning that they do not expect arguments.
Current version sets length to same value as original function.
Assigns `length` and `name` properties over the `Object.defineProperties` method
> fix: make `useDebounceCallback` and `useRafCallback` return proper fns

- README.md
- src/index.ts
- src/useMediaQuery/__docs__/example.stories.tsx
- src/useMediaQuery/__docs__/story.mdx
- src/useMediaQuery/__tests__/dom.tsx
- src/useMediaQuery/__tests__/ssr.tsx
- src/useMediaQuery/useMediaQuery.ts
- src/useResizeObserver/__docs__/story.mdx
Tracks the state of CSS media query.
- #33
> feat: new hook `useMediaQuery`

- src/index.ts
- src/useAsync/__docs__/example.stories.tsx
- src/useAsync/__docs__/story.mdx
- src/useAsync/__tests__/dom.ts
- src/useAsync/__tests__/ssr.ts
- src/useAsync/useAsync.ts
- utility/add-new-hook.js
> feat: new hook `useAsync`

- README.md
- src/index.ts
- src/useEventListener/__docs__/example.stories.tsx
- src/useEventListener/__docs__/story.mdx
- src/useEventListener/__tests__/dom.ts
- src/useEventListener/__tests__/ssr.ts
- src/useEventListener/useEventListener.ts
- src/useThrottledEffect/__docs__/story.mdx
- src/useThrottledState/__docs__/story.mdx
- src/util/misc.ts
Subscribes an event listener to the target, and automatically unsubscribes it on unmount.
- #33
> feat: new hook `useEventListener`

- README.md
- src/index.ts
- src/useSet/__docs__/example.stories.tsx
- src/useSet/__docs__/story.mdx
- src/useSet/__tests__/dom.ts
- src/useSet/__tests__/ssr.ts
- src/useSet/useSet.ts
Tracks the state of a `Set`
- #33
> feat: new hook `useSet`

- src/useCookieValue/__docs__/story.mdx
- src/useCookieValue/__tests__/dom.ts
- src/useCookieValue/useCookieValue.ts
- src/useLocalStorageValue/__docs__/example.stories.tsx
- src/useLocalStorageValue/__docs__/story.mdx
- src/useSessionStorageValue/__docs__/example.stories.tsx
- src/useSessionStorageValue/__docs__/story.mdx
- src/useStorageValue/__tests__/dom.ts
- src/useStorageValue/useStorageValue.ts
Some of the docs about syncing data across keys is unclear
Updated the wording a little
> docs: managing -> with the

- src/useMap/__docs__/story.mdx
- src/useSet/__docs__/story.mdx
The `useMap` and `useSet` signature notes were a little confusing
I reworded them
> docs: reword `useMap` and `useSet` signature notes

- src/__docs__/migrating-from-react-use.story.mdx
- src/useValidator/__docs__/story.mdx
add `useValidation` example to migration guide
> docs: add `useValidation` example to migration guide

- README.md
- src/useKeyboardEvent/__docs__/example.stories.tsx
- src/useKeyboardEvent/__docs__/story.mdx
- src/useKeyboardEvent/__tests__/dom.ts
- src/useKeyboardEvent/__tests__/ssr.ts
- src/useKeyboardEvent/useKeyboardEvent.ts
Also improve docs and arguments description.
BREAKING CHANGE: hook call signature has changed.
> refactor(useKeyboardEvent): improve code and change signature

- src/__docs__/migrating-from-react-use.story.mdx
`useAsync` gives wrong examples
correct the example
- fix: #343
> fix the examples of useAsync

- README.md
- src/index.ts
- src/useCustomCompareEffect/__docs__/example.stories.tsx
- src/useCustomCompareEffect/__docs__/story.mdx
- src/useCustomCompareEffect/__tests__/dom.ts
- src/useCustomCompareEffect/__tests__/ssr.ts
- src/useCustomCompareEffect/useCustomCompareEffect.ts
- src/util/__tests__/dom.ts
- src/util/misc.ts
- yarn.lock
Like `useEffect` but uses provided comparator function to validate dependencies change.
- #33
> feat: new hook `useCustomCompareEffect`

- src/__docs__/migrating-from-react-use.story.mdx
> docs: remove second param from `useAsync`, as per previous update

- README.md
- src/index.ts
- src/useConditionalEffect/__docs__/story.mdx
- src/useConditionalEffect/useConditionalEffect.ts
- src/useCustomCompareEffect/__docs__/example.stories.tsx
- src/useCustomCompareEffect/__docs__/story.mdx
- src/useCustomCompareEffect/useCustomCompareEffect.ts
- src/useDeepCompareEffect/__docs__/example.stories.tsx
- src/useDeepCompareEffect/__docs__/story.mdx
- src/useDeepCompareEffect/__tests__/dom.ts
- src/useDeepCompareEffect/__tests__/ssr.ts
- src/useDeepCompareEffect/useDeepCompareEffect.ts
It uses `@react-hookz/deep-equal` to compare dependencies.
> feat: new hook `useDeepCompareEffect`

- .prettierrc.js
- package.json
- yarn.lock
See https://github.com/react-hookz/eslint-config/pull/2 for context!
> Use prettier config

- src/__docs__/migrating-from-react-use.story.mdx
adds documentation on hot to migrate from useSetState hook
- #33
> docs: adds documentation on how to migrate from useSetState hook

- .github/workflows/ci-cd.yml
- .github/workflows/gh-pages.yml
- README.md
- src/index.ts
- src/useRafState/useRafState.ts
- src/useWindowSize/__docs__/example.stories.tsx
- src/useWindowSize/__docs__/story.mdx
- src/useWindowSize/__tests__/dom.ts
- src/useWindowSize/__tests__/ssr.ts
- src/useWindowSize/useWindowSize.ts
- yarn.lock
Tracks window inner dimensions.
- #33
> feat: implement useWindowSize hook

- src/useMediatedState/__docs__/example.stories.tsx
- src/useMediatedState/__docs__/story.mdx
- src/useMediatedState/__tests__/dom.ts
- src/useMediatedState/useMediatedState.ts
> fix(`useMediatedState`): make initial state be passed through mediator

- README.md
- jest.config.js
- src/__tests__/navigator.vibrate.ts
- src/__tests__/setup.ts
- src/index.ts
- src/useVibrate/__docs__/example.stories.tsx
- src/useVibrate/__docs__/story.mdx
- src/useVibrate/__tests__/dom.ts
- src/useVibrate/__tests__/ssr.ts
- src/useVibrate/useVibrate.ts
Introduce new hook `useVibrate` that provides vibration feedback using the Vibration API.
- #33
- fix: #683
> feat: `useVibration` hook implementation and docs

- README.md
- src/__docs__/migrating-from-react-use.story.mdx
- src/index.ts
- src/useList/__docs__/example.stories.tsx
- src/useList/__docs__/story.mdx
- src/useList/__tests__/dom.ts
- src/useList/__tests__/ssr.ts
- src/useList/useList.ts
Tracks a list and offers functions for manipulating it. The exact same API from react-use is retained.
I'm open to suggestions on improving the SSR tests. Due to my inexperience with SSR, I had hard time trying to figure out what to test there.
- #33
> feat(useList): port useList from react-use

- README.md
- src/index.ts
- src/useFunctionalState/__docs__/story.mdx
- src/useFunctionalState/__tests__/dom.ts
- src/useFunctionalState/__tests__/ssr.ts
- src/useFunctionalState/useFunctionalState.ts
- src/useSafeState/__docs__/story.mdx
- src/useSafeState/__tests__/dom.ts
close #530
Like `useState` but instead of raw state, state getter returned.
- #33
> feat: implement `useFunctionalState`

- src/useLocalStorageValue/__docs__/story.mdx
- src/useSessionStorageValue/__docs__/story.mdx
The function references are the ones from the previous implementation.
Update them to the new implementation.
- #1005
> docs(useLocalStorageValue & useSessionStorageValue): Fix function reference

- .github/workflows/ci-cd.yml
- src/__docs__/ImportPath.tsx
attempt to fix automerge action of workflows
> ci: fix dependabot automerge action
